language: julia
julia:
    - 0.6.4
addons:
    apt:
        packages:
            - libhdf5-serial-dev
sudo: enabled
after_success:
    - julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
