language: julia
julia:
    - 0.7
    - 1.0
addons:
    apt:
        packages:
            - libhdf5-serial-dev
sudo: enabled
after_success:
    # submit data to coveralls
    - julia -e 'using Pkg; cd(Pkg.dir("PorousMaterials")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

    # build the documentation site
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia -e 'using Pkg; cd(Pkg.dir("PorousMaterials")); include(joinpath("docs", "make.jl"))'
